# Server Configuration
server.port=8085
spring.application.name=math-courses-backend

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://127.0.0.1:61596;databaseName=math_courses_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Vinhha1234@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Google OAuth2 Client ID (Dành cho đăng nhập bằng Google)
google.client.id=748311830548-kn2es3vejt86ibtg3vkmfh2qk9quf48s.apps.googleusercontent.com

# MoMo Payment Gateway Configurations (Sandbox by default, replace with Production details when ready)
momo.partner-code=MOMOBKUN20180810
momo.access-key=klm056ha5sHM2839
momo.secret-key=esomatic70
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url=http://localhost:5173/payment/result
momo.ipn-url=https://your-domain.ngrok-free.app/api/payment/momo-ipn


