# ── Cấu hình môi trường Local (Bị .gitignore bỏ qua, KHÔNG commit lên Git) ──

# DB Credentials
spring.datasource.username=sa
spring.datasource.password=Vinhha1234@

# MoMo Credentials
momo.secret-key=esomatic70

# Gmail SMTP Credentials
spring.mail.username=vinhha20x@gmail.com
spring.mail.password=pwslmtnlelvvpymk
